/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountDashboards: typeof import('./src/pages/account/children/account-dashboards/AccountDashboards.vue')['default']
    AccountEdit: typeof import('./src/pages/account/children/account-edit/AccountEdit.vue')['default']
    AccountHistory: typeof import('./src/pages/account/children/account-history-orders/AccountHistory.vue')['default']
    AccountPage: typeof import('./src/pages/account/AccountPage.vue')['default']
    App: typeof import('./src/App.vue')['default']
    AppHeader: typeof import('./src/components/layout/app-header/components/AppHeader.vue')['default']
    AppHeaderAction: typeof import('./src/components/layout/app-header/components/app-header-actions/components/AppHeaderAction.vue')['default']
    AppHeaderActionCart: typeof import('./src/components/layout/app-header/components/app-header-actions/components/AppHeaderActionCart.vue')['default']
    AppHeaderActions: typeof import('./src/components/layout/app-header/components/app-header-actions/AppHeaderActions.vue')['default']
    AppHeaderActionSearch: typeof import('./src/components/layout/app-header/components/app-header-actions/components/AppHeaderActionSearch.vue')['default']
    AppLogo: typeof import('./src/components/layout/AppLogo.vue')['default']
    AuthPage: typeof import('./src/pages/auth/AuthPage.vue')['default']
    BaseButton: typeof import('./src/components/_uikit/buttons/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/components/_uikit/controls/other/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./src/components/_uikit/controls/other/BaseInput.vue')['default']
    Breadcrumbs: typeof import('./src/components/_uikit/other/Breadcrumbs.vue')['default']
    BreadCrumbs: typeof import('./src/components/_uikit/other/BreadCrumbs.vue')['default']
    Cart: typeof import('./src/components/layout/app-header/components/app-header-actions/components/Cart.vue')['default']
    DefaultPageLinkLogo: typeof import('./src/components/layout/app-header/components/DefaultPageLinkLogo.vue')['default']
    FormWrapper: typeof import('./src/pages/auth/components/FormWrapper.vue')['default']
    HomePage: typeof import('./src/pages/home/HomePage.vue')['default']
    LoginForm: typeof import('./src/pages/auth/components/LoginForm.vue')['default']
    Logo: typeof import('./src/components/layout/Logo.vue')['default']
    MoreLink: typeof import('./src/components/_uikit/other/MoreLink.vue')['default']
    NavMenu: typeof import('./src/components/layout/app-header/components/NavMenu.vue')['default']
    NotFoundPage: typeof import('./src/pages/NotFoundPage.vue')['default']
    PageContainer: typeof import('./src/components/layout/PageContainer.vue')['default']
    PageSection: typeof import('./src/components/layout/PageSection.vue')['default']
    PageWrapper: typeof import('./src/components/_uikit/wrappers/PageWrapper.vue')['default']
    ProductCard: typeof import('./src/components/_uikit/cards/ProductCard.vue')['default']
    RegistrationForm: typeof import('./src/pages/auth/components/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
