/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppHeader: typeof import('./src/components/layout/app-header/components/AppHeader.vue')['default']
    AppHeaderAction: typeof import('./src/components/layout/app-header/components/app-header-actions/components/AppHeaderAction.vue')['default']
    AppHeaderActionCart: typeof import('./src/components/layout/app-header/components/app-header-actions/components/AppHeaderActionCart.vue')['default']
    AppHeaderActions: typeof import('./src/components/layout/app-header/components/app-header-actions/AppHeaderActions.vue')['default']
    AppHeaderActionSearch: typeof import('./src/components/layout/app-header/components/app-header-actions/components/AppHeaderActionSearch.vue')['default']
    AppLogo: typeof import('./src/components/layout/AppLogo.vue')['default']
    Cart: typeof import('./src/components/layout/app-header/components/app-header-actions/components/Cart.vue')['default']
    DefaultPageLinkLogo: typeof import('./src/components/layout/app-header/components/DefaultPageLinkLogo.vue')['default']
    Logo: typeof import('./src/components/layout/Logo.vue')['default']
    NavMenu: typeof import('./src/components/layout/app-header/components/NavMenu.vue')['default']
    NotFoundPage: typeof import('./src/pages/NotFoundPage.vue')['default']
    PageContainer: typeof import('./src/components/layout/PageContainer.vue')['default']
    ProductCard: typeof import('./src/components/_uikit/cards/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
